In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("Placement.csv")

In [3]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [4]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    str
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    str
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    str
 6   hsc_s           215 non-null    str
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    str
 9   workex          215 non-null    str
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    str
 12  mba_p           215 non-null    float64
 13  status          215 non-null    str
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), str(8)
memory usage: 25.3 KB

In [5]:
#Quan=["ssc_p","hsc_p","etest_p","degree_p","mba_p","salary"]
#Qual=["gender","ssc_b","hsc_b","degree_t"]

In [6]:
dataset.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='str')

In [7]:
dir(dataset)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_select_dtypes_indices',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'degree_p',
 'degree_t',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'etest_p',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'gender',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'hsc_b',
 'hsc_p',
 'hsc_s',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mba_p',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'salary',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sl_no',
 'sort_index',
 'sort_values',
 'specialisation',
 'squeeze',
 'ssc_b',
 'ssc_p',
 'stack',
 'status',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'workex',
 'xs']

In [8]:
dataset["ssc_p"].dtypes

dtype('float64')

In [9]:
for columnName in dataset.columns:
    print(columnName)

sl_no
gender
ssc_p
ssc_b
hsc_p
hsc_b
hsc_s
degree_p
degree_t
workex
etest_p
specialisation
mba_p
status
salary

In [10]:
if(dataset["gender"].dtype=='O'):
    print("qual")
else:
    print("quan")

quan

In [11]:
quan=[]
qual=[]
for columnName in dataset.columns:
    #print(columnName)
    if(dataset[columnName].dtype=='O') or dataset[columnName].nunique() <= 5:
        #print("qual")
        qual.append(columnName)
    else:
        #print("quan")
        quan.append(columnName)

In [12]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [13]:
qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [14]:
def quanQual(dataset):
    quan=[]
    qual=[]
    for columnName in dataset.columns:
        #print(columnName)
        if(dataset[columnName].dtype=='O' or dataset[columnName].nunique() <= 5):
            #print("qual")
            qual.append(columnName)
        else:
            #print("quan")
            quan.append(columnName)
    return quan,qual

In [15]:
quanQual(dataset)

(['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'],
 ['gender',
  'ssc_b',
  'hsc_b',
  'hsc_s',
  'degree_t',
  'workex',
  'specialisation',
  'status'])

In [16]:
quan,qual=quanQual(dataset)

In [17]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [18]:
qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [19]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

# central tendency starts

In [20]:
dataset["ssc_p"].mean()

np.float64(67.30339534883721)

In [21]:
dataset["ssc_p"].median()

np.float64(67.0)

In [22]:
dataset["ssc_p"].mode()[0]

np.float64(62.0)

In [23]:
dataset.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [24]:
desc=pd.DataFrame()

In [25]:
desc=pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)

In [26]:
desc

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [27]:
desc["hsc_p"]["Median"]

nan

In [28]:
desc=pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)
for columnName in quan:
    numeric_col = pd.to_numeric(dataset[columnName], errors='coerce')
    desc.loc["Mean", columnName] = numeric_col.mean()
    desc.loc["Median", columnName] = numeric_col.median()
    desc.loc["Mode", columnName] = numeric_col.mode()[0] if not numeric_col.mode().empty else None

In [29]:
desc

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0

In [30]:
import numpy as np

In [31]:
np.percentile(dataset["salary"],25)

np.float64(nan)

In [32]:
np.percentile(dataset["mba_p"],25)

np.float64(57.945)

In [33]:
desc=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%"],columns=quan)
for columnName in quan:
   numeric_col = pd.to_numeric(dataset[columnName], errors='coerce')
   desc.loc["Mean", columnName] = numeric_col.mean()
   desc.loc["Median", columnName] = numeric_col.median()
   desc.loc["Mode", columnName] = numeric_col.mode()[0] if not numeric_col.mode().empty else None
   desc.loc["Q1:25%", columnName] = numeric_col.quantile(0.25)
   desc.loc["Q2:50%", columnName] = numeric_col.quantile(0.50)
   desc.loc["Q3:75%", columnName] = numeric_col.quantile(0.75)
   desc.loc["Q4:100%", columnName] = numeric_col.max()

In [34]:
desc

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215,89.4,97.7,91.0,98.0,77.89,940000.0

In [35]:
# 1. Initialize DataFrame with all necessary indices
index_labels = [
    "Mean", "Median", "Mode", 
    "Q1:25%", "Q2:50%", "Q3:75%", "Q4:100%", 
    "IQR", "1.5Rule", "Lesser", "Greater", "Min", "Max"
]
descriptive = pd.DataFrame(index=index_labels, columns=quan)

# 2. Compute statistics for each column
for columnName in quan:
    # Safely convert column to numeric
    numeric_col = pd.to_numeric(dataset[columnName], errors='coerce')
    descriptive.loc["Mean", columnName] = numeric_col.mean()
    descriptive.loc["Median", columnName] = numeric_col.median()
    descriptive.loc["Mode", columnName] = numeric_col.mode()[0] if not numeric_col.mode().empty else None
   
    # Percentiles
    q1 = numeric_col.quantile(0.25)
    q2 = numeric_col.quantile(0.50)
    q3 = numeric_col.quantile(0.75)
    q4 = numeric_col.max()
    
    # Store basic values using .loc[row, column]
    descriptive.loc["Q1:25%", columnName] = q1
    descriptive.loc["Q2:50%", columnName] = q2
    descriptive.loc["Q3:75%", columnName] = q3
    descriptive.loc["Q4:100%", columnName] = q4
    
    # IQR and Outlier Calculations
    iqr = q3 - q1
    rule1_5 = 1.5 * iqr
    
    descriptive.loc["IQR", columnName] = iqr
    descriptive.loc["1.5Rule", columnName] = rule1_5
    descriptive.loc["Lesser", columnName] = q1 - rule1_5
    descriptive.loc["Greater", columnName] = q3 + rule1_5
    
    # Min and Max
    descriptive.loc["Min", columnName] = numeric_col.min()
    descriptive.loc["Max", columnName] = numeric_col.max()

print(descriptive)

         sl_no      ssc_p      hsc_p   degree_p    etest_p      mba_p  \
Mean     108.0  67.303395  66.333163  66.370186  72.100558  62.278186
Median   108.0       67.0       65.0       66.0       71.0       62.0
Mode         1       62.0       63.0       65.0       60.0       56.7
Q1:25%    54.5       60.6       60.9       61.0       60.0     57.945
Q2:50%   108.0       67.0       65.0       66.0       71.0       62.0
Q3:75%   161.5       75.7       73.0       72.0       83.5     66.255
Q4:100%    215       89.4       97.7       91.0       98.0      77.89
IQR      107.0       15.1       12.1       11.0       23.5       8.31
1.5Rule  160.5      22.65      18.15       16.5      35.25     12.465
Lesser  -106.0      37.95      42.75       44.5      24.75      45.48
Greater  322.0      98.35      91.15       88.5     118.75      78.72
Min          1      40.89       37.0       50.0       50.0      51.21
Max        215       89.4       97.7       91.0       98.0      77.89

                salary
Mean     288655.405405
Median        265000.0
Mode          300000.0
Q1:25%        240000.0
Q2:50%        265000.0
Q3:75%        300000.0
Q4:100%       940000.0
IQR            60000.0
1.5Rule        90000.0
Lesser        150000.0
Greater       390000.0
Min           200000.0
Max           940000.0

In [36]:
descriptive["hsc_p"]["Min"]<descriptive["hsc_p"]["Lesser"]

np.True_

In [37]:
lesser=[]
greater=[]
for columnName in quan:
    if (descriptive[columnName]["Min"]<descriptive[columnName]["Lesser"]):
        lesser.append(columnName)
    if (descriptive[columnName]["Max"]>descriptive[columnName]["Greater"]):
        greater.append(columnName)

In [38]:
lesser

['hsc_p']

In [39]:
greater

['hsc_p', 'degree_p', 'salary']

In [40]:
for column in lesser:
    lesser_bound = descriptive.loc["Lesser", column]
    dataset.loc[dataset[column] < lesser_bound, column] = lesser_bound

# Capping upper bound outliers
for column in greater:
    greater_bound = descriptive.loc["Greater", column]
    dataset.loc[dataset[column] > greater_bound, column] = greater_bound

In [41]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,390000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,390000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [42]:
lesser1=[]
greater2=[]

for columnName in quan:
    if(descriptive[columnName]["Lesser"]>descriptive[columnName]["Min"]):
        lesser.append(columnName)
    if(descriptive[columnName]["Greater"]<descriptive[columnName]["Q4:100%"]):
        greater.append(columnName)

In [43]:
lesser1

[]

In [44]:
greater2

[]

In [45]:
dataset["ssc_p"].value_counts()

ssc_p
62.00    11
63.00    10
67.00     9
73.00     9
52.00     9
         ..
55.68     1
41.00     1
83.33     1
43.00     1
80.60     1
Name: count, Length: 103, dtype: int64

In [46]:
freqTable=pd.DataFrame(columns=["Unique_Values","Frequency","Relative_Frequency","Cumsum"])

In [47]:
freqTable

Empty DataFrame
Columns: [Unique_Values, Frequency, Relative_Frequency, Cumsum]
Index: []

In [48]:
freqTable["Unique_Values"]=dataset["ssc_p"].value_counts().index
freqTable["Frequency"]=dataset["ssc_p"].value_counts().values
freqTable["Relative_Frequency"]=(freqTable["Frequency"]/103)
freqTable["Cumsum"]=freqTable["Relative_Frequency"].cumsum()

In [49]:
def freqTable(columnName,dataset):
    freqTable=pd.DataFrame(columns=["Unique_Values","Frequency","Relative_Frequency","Cumsum"])
    freqTable["Unique_Values"]=dataset[columnName].value_counts().index
    freqTable["Frequency"]=dataset[columnName].value_counts().values
    freqTable["Relative_Frequency"]=(freqTable["Frequency"]/103)
    freqTable["Cumsum"]=freqTable["Relative_Frequency"].cumsum()
    return freqTable

In [50]:
freqTable("hsc_p",dataset)

    Unique_Values  Frequency  Relative_Frequency    Cumsum
0           63.00         14            0.135922  0.135922
1           62.00         12            0.116505  0.252427
2           67.00          9            0.087379  0.339806
3           60.00          9            0.087379  0.427184
4           64.00          8            0.077670  0.504854
..            ...        ...                 ...       ...
86          65.50          1            0.009709  2.048544
87          77.60          1            0.009709  2.058252
88          70.20          1            0.009709  2.067961
89          61.40          1            0.009709  2.077670
90          61.33          1            0.009709  2.087379

[91 rows x 4 columns]

In [51]:
dataset["ssc_p"].skew()

np.float64(-0.13264949031456927)

In [52]:
dataset["ssc_p"].kurtosis()

np.float64(-0.6075102066986688)

In [53]:
# 1. Initialize DataFrame with all necessary indices
index_labels = [
    "Mean", "Median", "Mode", 
    "Q1:25%", "Q2:50%", "Q3:75%", "Q4:100%", 
    "IQR", "1.5Rule", "Lesser", "Greater", "Min", "Max","kurtosis","skew"
]
descriptive = pd.DataFrame(index=index_labels, columns=quan)

# 2. Compute statistics for each column
for columnName in quan:
    # Safely convert column to numeric
    numeric_col = pd.to_numeric(dataset[columnName], errors='coerce')
    descriptive.loc["Mean", columnName] = numeric_col.mean()
    descriptive.loc["Median", columnName] = numeric_col.median()
    descriptive.loc["Mode", columnName] = numeric_col.mode()[0] if not numeric_col.mode().empty else None
   
    # Percentiles
    q1 = numeric_col.quantile(0.25)
    q2 = numeric_col.quantile(0.50)
    q3 = numeric_col.quantile(0.75)
    q4 = numeric_col.max()
    
    # Store basic values using .loc[row, column]
    descriptive.loc["Q1:25%", columnName] = q1
    descriptive.loc["Q2:50%", columnName] = q2
    descriptive.loc["Q3:75%", columnName] = q3
    descriptive.loc["Q4:100%", columnName] = q4
    
    # IQR and Outlier Calculations
    iqr = q3 - q1
    rule1_5 = 1.5 * iqr
    
    descriptive.loc["IQR", columnName] = iqr
    descriptive.loc["1.5Rule", columnName] = rule1_5
    descriptive.loc["Lesser", columnName] = q1 - rule1_5
    descriptive.loc["Greater", columnName] = q3 + rule1_5
    
    # Min and Max
    descriptive.loc["Min", columnName] = numeric_col.min()
    descriptive.loc["Max", columnName] = numeric_col.max()

    # Skew and Kurtosis
    descriptive.loc["kurtosis", columnName] = numeric_col.kurtosis()
    descriptive.loc["skew", columnName] = numeric_col.skew()

print(descriptive)

          sl_no      ssc_p      hsc_p   degree_p    etest_p      mba_p  \
Mean      108.0  67.303395  66.334744  66.358558  72.100558  62.278186
Median    108.0       67.0       65.0       66.0       71.0       62.0
Mode          1       62.0       63.0       65.0       60.0       56.7
Q1:25%     54.5       60.6       60.9       61.0       60.0     57.945
Q2:50%    108.0       67.0       65.0       66.0       71.0       62.0
Q3:75%    161.5       75.7       73.0       72.0       83.5     66.255
Q4:100%     215       89.4      91.15       88.5       98.0      77.89
IQR       107.0       15.1       12.1       11.0       23.5       8.31
1.5Rule   160.5      22.65      18.15       16.5      35.25     12.465
Lesser   -106.0      37.95      42.75       44.5      24.75      45.48
Greater   322.0      98.35      91.15       88.5     118.75      78.72
Min           1      40.89      42.75       50.0       50.0      51.21
Max         215       89.4      91.15       88.5       98.0      77.89
kurtosis   -1.2   -0.60751   0.086901   -0.09749   -1.08858  -0.470723
skew        0.0  -0.132649   0.162611   0.204164   0.282308   0.313576

                 salary
Mean      277648.648649
Median         265000.0
Mode           300000.0
Q1:25%         240000.0
Q2:50%         265000.0
Q3:75%         300000.0
Q4:100%        390000.0
IQR             60000.0
1.5Rule         90000.0
Lesser         150000.0
Greater        390000.0
Min            200000.0
Max            390000.0
kurtosis      -0.239837
skew             0.8067