In [2]:
#import pandas for operation based for files
import pandas as pd

In [3]:
#getting dataset
dataset=pd.read_csv("DataSet-SLAssignment.csv")
dataset

    S.No  YearsOfExperience   Salary
0      1                1.0   125000
1      2                1.5   175000
2      3                2.0   200000
3      4                2.5   500000
4      5                4.0  1200000
5      7                4.5  1400000
6      8                5.0  1500000
7      9                5.1  1510000
8     10                6.0  1700000
9     11                6.3  1730000
10    12                6.5  1750000
11    13                7.0  1850000
12    14                7.4  1860000
13    15                7.8  1890000
14    16                8.0  2100000
15    17                8.1  2110000
16    18                8.3  2200000
17    19                8.4  2250000
18    20                8.8  2300000
19    21                9.0  2500000
20    22                9.1  2550000
21    23                9.4  2700000
22    24                9.9  2750000
23    25               10.0  3200000
24    26               10.4  3300000
25    27               10.5  3400000
26    28               10.9  3800000
27    29               11.0  4000000
28    29               12.0  4300000
29    30               12.5  4400000

In [4]:
#input
independent=dataset[["YearsOfExperience"]]
independent

    YearsOfExperience
0                 1.0
1                 1.5
2                 2.0
3                 2.5
4                 4.0
5                 4.5
6                 5.0
7                 5.1
8                 6.0
9                 6.3
10                6.5
11                7.0
12                7.4
13                7.8
14                8.0
15                8.1
16                8.3
17                8.4
18                8.8
19                9.0
20                9.1
21                9.4
22                9.9
23               10.0
24               10.4
25               10.5
26               10.9
27               11.0
28               12.0
29               12.5

In [5]:
#salary input
dependent=dataset[["Salary"]]
dependent

     Salary
0    125000
1    175000
2    200000
3    500000
4   1200000
5   1400000
6   1500000
7   1510000
8   1700000
9   1730000
10  1750000
11  1850000
12  1860000
13  1890000
14  2100000
15  2110000
16  2200000
17  2250000
18  2300000
19  2500000
20  2550000
21  2700000
22  2750000
23  3200000
24  3300000
25  3400000
26  3800000
27  4000000
28  4300000
29  4400000

In [6]:
#all regression model will be imported from sklearn'
#this will be used to split the training set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)
y_test

     Salary
2    200000
28  4300000
13  1890000
10  1750000
26  3800000
24  3300000
27  4000000
11  1850000
17  2250000

In [7]:
#y=mx+c
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [8]:
#mass value
m_weight=regressor.coef_
m_weight

array([[327900.05499378]])

In [9]:
#initial value or base
c_bias=regressor.intercept_
c_bias

array([-298024.67040889])

In [10]:
#get the prediction output based on test input
y_predict=regressor.predict(x_test)
y_predict

array([[ 357775.43957868],
       [3636775.9895165 ],
       [2259595.75854261],
       [1833325.6870507 ],
       [3276085.92902334],
       [3112135.90152645],
       [3308875.93452272],
       [1997275.71454759],
       [2456335.79153888]])

In [11]:
#evaluation metrics
from sklearn.metrics import r2_score

In [12]:
#if r2 score value near to 1 - good model else not good model
r_score=r2_score(y_test,y_predict)
r_score

0.8989703751673794

In [13]:
#create a file to save model
import pickle
filename="ML_Supervise_Regression_Linear.sav"

In [14]:
#save the model into file
pickle.dump(regressor,open(filename,"wb"))

In [15]:
#load the model
loaded_model=pickle.load(open(filename,"rb"))

In [16]:
result=loaded_model.predict([[15]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [17]:
result

array([[4620476.15449785]])